# Generated by Django 3.0.3 on 2020-02-09 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('owner_Fname', models.CharField(max_length=200)),
                ('owner_Lname', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_item', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=200)),
                ('maintain_date', models.DateTimeField(verbose_name='date Maintainance')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_item', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=200)),
                ('install_date', models.DateTimeField(verbose_name='date installed')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Owner')),
            ],
        ),
    ]
