# Generated by Django 3.0.3 on 2020-02-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installation',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='maintainance',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
