# Generated by Django 3.0.3 on 2020-02-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200210_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainance',
            name='Remarks',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
